Coinjoin: update fees
WalletWasabi/WasabiDoc pull request #1747
Opened 2024-06-19 10:48 UTC by MarnixCroes

2024-06-19 18:12 UTC, yahiheb requested changes

2024-06-19 18:12 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +The default values are 0% coordination fee and maximum 150 sat/vByte mining fee.
```suggestion
The default values are 0% coordination fee and maximum 150 sat/vByte mining fee rate.
```

2024-06-19 18:12 UTC, yahiheb commented on docs/using-wasabi/CoinJoin.md
> +Although the coordinator cannot steal money from the coinjoin participants, it could set a high mining and/or coordinator fee. This could make the participating users pay a lot (unnecessarily). To pr
```suggestion
Although the coordinator cannot steal money from the coinjoin participants, it could set a high mining fee rate and/or a high coordination fee.
This would make the participants pay a lot (unnecessarily).
To prevent such behavior the Wasabi client can configure the maximum mining fee rate and the maximum coordination fee it is willing to pay per round.
If one of these is higher than the entered values, the client will not participate in the coinjoin.
```

2024-06-20 06:48 UTC, MarnixCroes commented on docs/using-wasabi/CoinJoin.md
> +Although the coordinator cannot steal money from the coinjoin participants, it could set a high mining and/or coordinator fee. This could make the participating users pay a lot (unnecessarily). To pr
done

2024-06-20 06:51 UTC, merged