add latest coordinator configs to glossary
WalletWasabi/WasabiDoc pull request #1760
Opened 2024-07-03 09:47 UTC by MarnixCroes

closes https://github.com/WalletWasabi/WasabiDoc/issues/1755 https://github.com/WalletWasabi/WasabiDoc/issues/1738 https://github.com/WalletWasabi/WasabiDoc/issues/1736

For GUI users the tooltip is self explanatory.
Adding it here to the glossary for non GUI users and a good way to have it at least mentioned somewhere in the docs, including the default values.

2024-07-03 15:33 UTC, yahiheb requested changes

2024-07-03 15:33 UTC, yahiheb commented on docs/glossary/Glossary-PrivacyWasabi.md
> +### Absolute min input count
How about changing this to `Min input count` and put it with the other coordinator configs?

2024-07-03 15:33 UTC, yahiheb commented on docs/glossary/Glossary-PrivacyWasabi.md
> +The default value is 0.0.
```suggestion
The maximum coordination fee rate the client is willing to accept to participate into a round.
The default value is 0%.
```

2024-07-03 15:33 UTC, yahiheb commented on docs/glossary/Glossary-PrivacyWasabi.md
> +The default value is 150.
```suggestion
The maximum mining fee rate in sat/vByte the client is willing to pay to participate into a round.
The default value is 150 s/vb.
```

2024-07-04 08:23 UTC, MarnixCroes commented on docs/glossary/Glossary-PrivacyWasabi.md
> +### Absolute min input count
adding them here is aimed for daemon users. 
`AbsoluteMinInputCount` is the actual name of the property, so I prefer this.
for GUI users with the tooltip it should be self-explanatory

2024-07-04 10:52 UTC, yahiheb approved these changes

2024-07-04 10:52 UTC, merged

2024-07-06 23:51 UTC, lontivero commented
@MarnixCroes this documentation contains a common problem that confused rates with percentages. Yes, rates can be expressed as percentages when the relation is between two magnitudes of the same kind but it would be preferable to use rates everywhere and avoid percentages.

2024-07-08 07:53 UTC, MarnixCroes commented
> @MarnixCroes this documentation contains a common problem that confused rates with percentages. Yes, rates can be expressed as percentages when the relation is between two magnitudes of the same kind but it would be preferable to use rates everywhere and avoid percentages.

fixed in https://github.com/WalletWasabi/WasabiDoc/pull/1775