FAQ: How do I find a coordinator?
WalletWasabi/WasabiDoc pull request #1785
Opened 2024-07-16 08:28 UTC by MarnixCroes

I think it's safe to list wasabist and wabisator, they have been around for a bit of time now and are useful for a lot of people.
And they are used/linked with support requests.
But still put the warning there in case they would do something malicious, and that it is not an endorsement to use them.

2024-07-16 20:21 UTC, yahiheb requested changes

2024-07-16 20:21 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +### How do I find a coordinator?
It makes more sense to move this above `How do I change the coordinator?`.

2024-07-16 20:21 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +- Users can do their own discovery with tools like [Wasabi Nostr](https://github.com/Kukks/wasabinostr), which discovers Wasabi coordinators over Nostr.
```suggestion
- Users can do their own discovery with tools like [Wasabi Nostr](https://github.com/Kukks/wasabinostr), which discovers Wabisabi coordinators over Nostr.
```

2024-07-16 20:21 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +- Public announcement websites, such as https://wasabist.io/, https://wabisator.com/, [Liquisabi bot (Twitter)](https://x.com/liquisabi), [Liquisabi bot (Nostr)](https://njump.me/npub1u4rl3zlfa2efxsl
```suggestion
- Public announcement websites, such as [wasabist](https://wasabist.io), [wabisator](https://wabisator.com), [Liquisabi bot (Twitter)](https://x.com/liquisabi), [Liquisabi bot (Nostr)](https://njump.me/npub1u4rl3zlfa2efxslhypf4v6r8va5e0c9smxyr5676pxkyk0chn33s0teswa)
```

2024-07-17 07:36 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +### How do I find a coordinator?
done

2024-07-17 07:37 UTC, MarnixCroes commented on docs/FAQ/FAQ-UseWasabi.md
> +- Users can do their own discovery with tools like [Wasabi Nostr](https://github.com/Kukks/wasabinostr), which discovers Wasabi coordinators over Nostr.
it discovers Wasabi coordinators, not WabiSabi

2024-07-17 07:37 UTC, merged

2024-07-17 17:43 UTC, yahiheb commented on docs/FAQ/FAQ-UseWasabi.md
> +- Users can do their own discovery with tools like [Wasabi Nostr](https://github.com/Kukks/wasabinostr), which discovers Wasabi coordinators over Nostr.
> A simple application that allows you to discover Wabisabi coordinators over Nostr and quickly configure your Wasabi wallet to use them.

According to the description of that tool.